name: Build Docker images

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: [19]
    env:
      repo: "govpf/node"
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.3.0

    - name: Build
      uses: docker/build-push-action@v2.4.0
      with:
        context: .
        file: ./${{ matrix.versions }}/Dockerfile
        platforms: linux/amd64
        pull: true
        push: true
        tags: |
          ${{ env.repo }}:${{ matrix.versions }}
